export const DUsers = [
  {
    id:1,
    profilePicture: "assets/person/1.JPG",
    username: "Tarun kumar",
  },
  {
    id:2,
    profilePicture: "assets/person/2.JPG",
    username: "Fazeel Ahmed",
  },
  {
    id:3,
    profilePicture: "assets/person/3.JPG",
    username: "Aditya Godiyal",
  },
  {
    id:4,
    profilePicture: "assets/person/4.JPG",
    username: "Abhishek Singh",
  },
  {
    id:5,
    profilePicture: "assets/person/5.JPG",
    username: "Aryan Singh",
  },
  {
    id:6,
    profilePicture: "assets/person/6.JPG",
    username: "Sunita Singh",
  },
  {
    id:7,
    profilePicture: "assets/person/7.JPG",
    username: "Gullu",
  },
  {
    id:8,
    profilePicture: "assets/person/8.JPG",
    username: "Salman (Bhaijaan)",
  },
  {
    id:9,
    profilePicture: "assets/person/9.JPG",
    username: "Nikhil",
  },
  {
    id:10,
    profilePicture: "assets/person/10.JPG",
    username: "Aryan Singh",
  },
];

export const DPosts = [
  {
    id: 1,
    desc: "Love For All, Hatred For None.",
    photo: "../src/assets/post/post1.PNG",
    date: "50 mins ago",
    userId: 1,
    like: 3200,
    comment: 9,
  },
  {
    id: 2,
    desc: "Brossover",
    photo: "/src/assets/post/post2.jpg",
    date: "15 mins ago",
    userId: 2,
    like: 2000,
    comment: 12,
  },
  {
    id: 3,
    desc: "Every moment is a fresh beginning.",
    photo: "assets/post/post3.JPG",
    date: "1 hour ago",
    userId: 3,
    like: 6100,
    comment: 200,
  },
  {
    id: 4,
    desc: "Chotuuuu",
    photo: "assets/post/post4.JPG",
    date: "4 hours ago",
    userId: 4,
    like: 7000,
    comment: 300,
  },
  {
    id: 5,
    desc: "family....",
    photo: "assets/post/post5.JPG",
    date: "5 hours ago",
    userId: 5,
    like: 23000,
    comment: 5000,
  },
  {
    id: 6,
    desc: "Posting the post",
    photo: "assets/post/post6.JPG",
    date: "1 day ago",
    userId: 6,
    like: 440,
    comment: 600,
  },
  {
    id: 7,
    desc: "Posting the post",
    photo: "assets/post/post7.JPG",
    date: "2 days ago",
    userId: 7,
    like: 1552,
    comment: 123,
  },
  {
    id: 8,
    desc: "Posting the post",
    photo: "assets/post/post8.JPG",
    date: "3 days ago",
    userId: 8,
    like: 15,
    comment: 1,
  },
  {
    id: 9,
    desc: "Posting the post",
    photo: "assets/post/post9.JPG",
    date: "5 days ago",
    userId: 9,
    like: 11,
    comment: 2,
  },
  {
    id: 10,
    desc: "Posting the post",
    photo: "assets/post/post10.JPG",
    date: "1 week ago",
    userId: 10,
    like: 104,
    comment: 12,
  },
  {
    id: 11,
    desc: "Posting the post",
    photo: "assets/post/post11.JPG",
    date: "1 week ago",
    userId: 11,
    like: 104,
    comment: 12,
  },
  {
    id: 12,
    desc: "Posting the post",
    photo: "assets/post/post12.JPG",
    date: "1 week ago",
    userId: 12,
    like: 104,
    comment: 12,
  },
  {
    id: 13,
    desc: "Walk the way",
    photo: "assets/post/post13.JPG",
    date: "1 week ago",
    userId: 13,
    like: 10400,
    comment: 1200,
  },
];
